# Generated by Django 5.0.6 on 2024-05-13 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project_type', models.CharField(choices=[('СТЕНА', 'СТЕНА'), ('КОМНАТА', 'КОМНАТА'), ('ГОСТИННАЯ', 'ГОСТИННАЯ')], default='СТЕНА', max_length=20)),
                ('width_a', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width_b', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width_c', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width_d', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interior_walls', models.BooleanField(default=False)),
                ('external_walls', models.BooleanField(default=False)),
                ('floor', models.BooleanField(default=False)),
                ('baseboard', models.BooleanField(default=False)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.firm')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('norm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.brand')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.group')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.unit')),
            ],
        ),
    ]
