# Generated by Django 5.0.6 on 2024-05-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_brand_name_alter_firm_name_alter_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='LIVING_ROOM_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ROOM_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='material',
            field=models.ManyToManyField(blank=True, to='info.material'),
        ),
        migrations.AddField(
            model_name='project',
            name='wall_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
