# Generated by Django 5.0.6 on 2024-05-14 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_project_living_room_area_project_room_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='baseboard',
        ),
        migrations.RemoveField(
            model_name='project',
            name='external_walls',
        ),
        migrations.RemoveField(
            model_name='project',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='interior_walls',
        ),
        migrations.RemoveField(
            model_name='project',
            name='material',
        ),
        migrations.CreateModel(
            name='ProjectMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_material', models.CharField(choices=[('ВНУТРЕННИЕ СТЕНЫ', 'ВНУТРЕННИЕ СТЕНЫ'), ('ВНЕШНИЕ СТЕНЫ', 'ВНЕШНИЕ СТЕНЫ'), ('ПОЛ', 'ПОЛ'), ('ПАТАЛОК', 'ПАТАЛОК')], default=None, max_length=20)),
                ('material', models.ManyToManyField(blank=True, to='info.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.project')),
            ],
        ),
    ]
