# Generated by Django 5.0.6 on 2024-05-14 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_remove_project_baseboard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmaterial',
            name='material',
        ),
        migrations.AlterField(
            model_name='projectmaterial',
            name='type_material',
            field=models.CharField(blank=True, choices=[('ВНУТРЕННИЕ СТЕНЫ', 'ВНУТРЕННИЕ СТЕНЫ'), ('ВНЕШНИЕ СТЕНЫ', 'ВНЕШНИЕ СТЕНЫ'), ('ПОЛ', 'ПОЛ'), ('ПАТАЛОК', 'ПАТАЛОК')], max_length=20),
        ),
        migrations.AddField(
            model_name='projectmaterial',
            name='material',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='info.material'),
        ),
    ]
