# Generated by Django 5.0.6 on 2024-05-14 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_remove_projectmaterial_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.material'),
        ),
    ]
