# Generated by Django 5.0.6 on 2024-05-15 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_project_ceiling_area_project_ceiling_area_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='full_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая площадь'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ceiling_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая Площадь потолка'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ceiling_area_a',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь потолка A'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ceiling_area_b',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь потолка B'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ceiling_area_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь потолка C'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ceiling_area_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь потолка D'),
        ),
        migrations.AlterField(
            model_name='project',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.firm', verbose_name='Фирма'),
        ),
        migrations.AlterField(
            model_name='project',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='project',
            name='living_room_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь гостиной'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('СТЕНА', 'СТЕНА'), ('КОМНАТА', 'КОМНАТА'), ('ГОСТИННАЯ', 'ГОСТИННАЯ')], default='СТЕНА', max_length=20, verbose_name='Тип проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='room_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь комнаты'),
        ),
        migrations.AlterField(
            model_name='project',
            name='wall_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая Площадь стены'),
        ),
        migrations.AlterField(
            model_name='project',
            name='wall_area_a',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь стены A'),
        ),
        migrations.AlterField(
            model_name='project',
            name='wall_area_b',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь стены B'),
        ),
        migrations.AlterField(
            model_name='project',
            name='wall_area_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь стены C'),
        ),
        migrations.AlterField(
            model_name='project',
            name='wall_area_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь стены D'),
        ),
        migrations.AlterField(
            model_name='project',
            name='width_a',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ширина A'),
        ),
        migrations.AlterField(
            model_name='project',
            name='width_b',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ширина B'),
        ),
        migrations.AlterField(
            model_name='project',
            name='width_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ширина C'),
        ),
        migrations.AlterField(
            model_name='project',
            name='width_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ширина D'),
        ),
    ]
