# Generated by Django 5.0.6 on 2024-05-15 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_remove_project_full_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmaterial',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_materials', to='info.project'),
        ),
    ]
