# Generated by Django 5.0.6 on 2024-05-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_alter_projectmaterial_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmaterial',
            name='summa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
